config/routes.rb
Rails.application.routes.draw do

  resources :countdowns, only: [:show, :index, :edit, :create, :destroy, :new, :update]
  get '/countdowns/new/next', to: 'countdowns#next', as: :next
  get '/countdowns/new/preview', to: 'countdowns#preview', as: :preview

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  devise_scope :user do
    authenticated :user do
      root 'countdowns#index'
    end
		
    unauthenticated do
      root 'devise/sessions#new'
    end
  end

  resources :users, only: [:edit, :show, :update]

  # Begin StaticPages Controller
  get '/landing', to: 'static_pages#landing', as: :landing
	get '/about', to: 'static_pages#about', as: :about
	get '/attributions', to: 'static_pages#attributions', as: :attributions
  get '/random', to: 'static_pages#random', as: :random
  # End StaticPages Controller


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/countdown.rb
class Countdown < ApplicationRecord
  mount_uploader :main_image, CountdownMainImageUploader
  mount_uploader :background_image, CountdownBackgroundImageUploader

  belongs_to :user
  validates :name, presence: true, length: { maximum: 150 }
  validates :date, presence: true
  validate :date_cannot_be_in_the_past

  def date_format(format)
    date.strftime(format)
  end

  def html_template
    template = %(
      <html lang="en">
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
          <meta name="description" content="">
          <meta name="author" content="">

          <title>#{name}</title>

          <!-- Bootstrap core CSS -->
          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

          <!-- Custom styles for this template -->
          <link href="css/flipclock.css" rel="stylesheet">
          <link href="css/countdown.css" rel="stylesheet">

          <!-- Custom Javascript -->
          <script src='https://code.jquery.com/jquery-3.1.0.min.js'></script>
          <script src="js/flipclock.js"></script>
          <script src="js/countdown.js"></script>
        </head>
        <body>
          <div class="countdown" style="background: url('image/background_image.jpg')">
            <header class="masthead">
              <div class="intro-body">
                <div class="container">
                  <div class="text-center">
                    <h3 class="brand-heading margin" style="color: #{title_color}">#{name}</h3>
                    <img src="image/main_image.jpg"  class="img-responsive img-circle margin" alt="Me" style="display:inline" width="250" height="250">
                    <div class="text-center">
                      <div class="flip-counter clock flip-clock-wrapper" style=""></div>
                    </div>
                  </div>
                </div>
              </div>
            </header>
          </div>

          <input id="countdown-date" type="hidden" value="#{date}">
       
          <style>
            .flip-clock-label { 
              color: #{ labels_color } !important;
            }

            .flip-clock-wrapper ul li a div div.inn {
              color: #{ time_color } !important;
              background-color: #{ clock_background_color } !important;
            }
          </style>
        </body>
      </html>
    )
    return template
  end

  protected

    def date_cannot_be_in_the_past
      if date.present? && date < Date.today
        errors.add(:date, "can't be in the past")
      end
    end
end

app/controllers/countdowns_controller.rb
require 'zip'

class CountdownsController < ApplicationController
  def index
  end

  def show
    @countdown = Countdown.find(params[:id])

    respond_to do |format|
      format.html
      format.zip do
        compressed_filestream = Zip::OutputStream.write_buffer do |zos|
          zos.put_next_entry "countdown/image/main_image.jpg"
          zos.print File.open(File.join(Rails.root, "/public/#{@countdown.main_image.thumb.url}")).read

          zos.put_next_entry "countdown/image/background_image.jpg"
          zos.print File.open(File.join(Rails.root, "/public/#{@countdown.background_image.url}")).read

          zos.put_next_entry "countdown/css/countdown.css"
          zos.print File.open(File.join(Rails.root, "/public/countdown_zip/countdown.css")).read

          zos.put_next_entry "countdown/css/flipclock.css"
          zos.print File.open(File.join(Rails.root, "/public/countdown_zip/flipclock.css")).read

          zos.put_next_entry "countdown/js/countdown.js"
          zos.print File.open(File.join(Rails.root, "/public/countdown_zip/countdown.js")).read

          zos.put_next_entry "countdown/js/flipclock.js"
          zos.print File.open(File.join(Rails.root, "/public/countdown_zip/flipclock.js")).read

          zos.put_next_entry "countdown/index.html"
          zos.print @countdown.html_template
 
        end
        compressed_filestream.rewind
        send_data compressed_filestream.read, filename: "countdown.zip"

      end
    end
  end

  def edit
    @countdown = Countdown.find(params[:id])
  end

  def update
    @countdown = Countdown.find(params[:id])
    #@countdown = Countdown.new(countdown_params)
    @countdown.assign_attributes(countdown_params)
    if !params[:countdown][:local_main_image].empty?
      @countdown.main_image = File.open(File.join(Rails.root, "/public/#{params[:countdown][:local_main_image]}"))
    end

    if !params[:countdown][:local_background_image].empty?
      @countdown.background_image = File.open(File.join(Rails.root, "/public/#{params[:countdown][:local_background_image]}"))
    end

    if @countdown.save
      flash[:sucess] = "New Countdown Created!"
      redirect_to @countdown
    else
      render 'edit'
    end

  end

  def create
    @countdown = Countdown.new(countdown_params)
    if !params[:countdown][:local_main_image].empty?
      @countdown.main_image = File.open(File.join(Rails.root, "/public/#{params[:countdown][:local_main_image]}"))
    end

    if !params[:countdown][:local_background_image].empty?
      @countdown.background_image = File.open(File.join(Rails.root, "/public/#{params[:countdown][:local_background_image]}"))
    end

    @countdown.user = current_user
    if @countdown.save
      flash[:sucess] = "New Countdown Created!"
      redirect_to @countdown
    else
      render 'new'
    end
  end

  def destroy
    @countdown = Countdown.find(params[:id])
    @countdown.destroy
    redirect_to current_user
  end

  def new
    @countdown = Countdown.new
  end

  def next
    respond_to do |format|
      @countdown = Countdown.new(countdown_params)
      if !params[:countdown][:local_main_image].empty?
        @countdown.main_image = File.open(File.join(Rails.root, "/public/#{params[:countdown][:local_main_image]}"))

      end

      if !params[:countdown][:local_background_image].empty?
        @countdown.background_image = File.open(File.join(Rails.root, "/public/#{params[:countdown][:local_background_image]}"))
      end
 
      @countdown.user = current_user
      @valid = @countdown.valid?
      if @valid
        format.json {
          render json: { valid: @valid }
        }
      else
        format.json {
          render json: { valid: @valid, 
                         error: @countdown.errors.full_messages.first }
        }
      end
    end
  end

  def preview
    respond_to do |format|
      @countdown = Countdown.new(countdown_params)
      @countdown.user = current_user
      @valid = @countdown.valid?
      if @valid
        format.json {
          render json: { valid: @valid }
        }
      else
        format.json {
          render json: { valid: @valid, 
                         error: @countdown.errors.full_messages.first }
        }
      end
    end
   end

  private

    def countdown_params
      params.require(:countdown).permit(:countdown, :name, :date, :main_image, 
        :background_image, :title_color, :labels_color, 
        :clock_background_color, :time_color)
    end

end

app/helpers/countdown_helper.rb
module CountdownHelper
  def params_valid?(countdown)
    countdown.assign_attributes(countdown_params)
    countdown.valid?
  end

  private

    def countdown_params
      params.require(:countdown).permit(:name, :date, :main_image, :background_image)
    end
end

app/views/countdowns/_countdown.html.erb
<div class='countdown' style="background: url(<%=countdown.background_image%>) no-repeat center center fixed;">
  <header class="masthead">
    <div class="intro-body">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h3 class="brand-heading margin" style="color: <%= countdown.title_color %>;"><%=countdown.name%></h3>
				    <img src="<%=countdown.main_image%>"  class="img-fluid rounded-circle margin" alt="Me" style="display:inline" width="250" height="250">
            <div class="flip-counter clock flip-clock-wrapper" style="margin:2em;"></div>
          </div>
        </div>
      </div>
    </div>
  </header>
</div>

app/views/countdowns/_countdown_actions_modal.html.erb
<!--Countdown actions modal-->
<div id="countdown-actions-modal">
  <!--THIS IS IMPORTANT! to close the modal, the class name has to match the name given on the ID  class="close-animatedModal" -->
  <div id="closebt-container" class="close-countdown-actions-modal"> 
    <img class="closebt" src="/images/closebt.svg">
  </div>
            
  <div class="modal-content">
    <!--Your modal content goes here-->
  </div>
</div>

app/views/countdowns/_countdown_modal.html.erb
<!--Countdown actions modal-->
<div id="countdown-modal">
  <!--THIS IS IMPORTANT! to close the modal, the class name has to match the name given on the ID  class="close-animatedModal" -->
  <div id="closebt-container" class="close-countdown-modal"> 
    <img class="closebt" src="/images/closebt.svg">
  </div>
            
  <div class="countdown-modal-content">
    <div class="countdown" style='background: url(<%=@countdown.background_image.url%>'>
  <header class="masthead">
<!--
    <div id="animated-modal-toggle" class="text-center">
      <a href="#countdown-actions-modal" class="glyphicon glyphicon-modal-window" style="color: <%#=@countdown.title_color%>"></a>

    </div>-->
    <div class="intro-body">
      <div class="container">
        <div class="text-center">
          <h3 class="brand-heading margin" style="color: <%=@countdown.title_color%>"><%=@countdown.name%></h3>
			    <img src="<%=@countdown.main_image.thumb.url%>"  class="img-responsive img-circle margin" alt="Me" style="display:inline" width="250" height="250">
          <div class="text-center">
            <div class="flip-counter clock flip-clock-wrapper" style=""></div>
          </div>
        </div>
      </div>
    </div>
  </header>
</div>

  </div>
</div>

app/views/countdowns/_preview.html.erb
<div class="modal fade in" id="preview-modal" role="dialog">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title"> Countdown Preview </h4>
			</div>
			<div class="countdown-modal-body">
			  
      </div>
<!--
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
-->
		</div>
	</div>
</div>

app/views/countdowns/edit.html.erb
<%= render '/countdowns/preview.html.erb' %>
<% provide(:title, "Edit Countdown") %>
<%= form_for(@countdown, :html => { class: "countdown-form g-primary-card", id: "ct-edit-form" }) do |f| %>

  <h1>Edit Countdown</h1>

  <%= render 'shared/error_messages' %>

<h2>Date and Title</h2>
<div class="text-center g-mb-40">
  <div class="form-group">
    <%= f.label :name %>
    <br>
  	<%= f.text_field :name, class: "form-control", placeholder: "Enter countdown name", style: "display: inline; width: 66%;" %>
 </div>
  
  <div class="form-group">
  	<%= f.label :date %>
    <br>
    <%= f.date_field :date, class: "form-control", style: "display: inline; width: 66%;" %>
  </div>
</div>
  <hr class="g-mv-20 light-gray-border clear-both">
  <h2>Colors</h2>

  <div class="g-mb-40 text-center"> 
    <div class="form-group">
  	  <%= f.label :title_color, "Title Color:" %>
      <div>
  		  <%= f.text_field :title_color, class: "form-control", style: "display: inline; width: 66%;" %>
      </div>
  	</div>
    
  
    <div class="form-group">
  		<%= f.label :labels_color, "Labels' Color:" %>
      <div>
        <%= f.text_field :labels_color, class: "form-control", style: "display: inline; width: 66%;" %>
      </div>
    </div>

    <div class="form-group">
  	  <%= f.label :time_color, "Time Color:" %>
      <div>
  		  <%= f.text_field :time_color, class: "form-control", style: "display: inline; width: 66%;" %>
      </div>
    </div>
  
    <div class="form-group">
  	  <%= f.label :clock_background_color, "Clock Background Color:" %>
      <div>
        <%= f.text_field :clock_background_color, class: "form-control", style: "display: inline; width: 66%;" %>
      </div>
    </div>
  </div>
  <hr class="g-mv-20 light-gray-border clear-both">
<h2>Images</h2>

  <div class="form-group">
    <%= f.hidden_field :local_main_image, class: "hidden", value: "" %>
    <%= f.hidden_field :local_background_image, class: "hidden", value: "" %>

    <p class="g-label">Countdown Image:</p>
    <p class="secondary-text g-ml-10">Choose one of our images or upload your own</p>
  <div>
    <div class="row main-image-scroll"> 
      <% 7.times do |n| %>
        <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
          <div class="text-center row">
            <img src="/main_images/main_image<%=n + 1%>.jpg" alt="Default Countdown Image" style="max-width: 120px; max-height: 120px;" class="g-mb-5 default-image imgFrame">
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="text-center">
    <label for="countdown_main_image" class="btn font-size-16 font-weight-600 g-mb-10 g-btn-secondary image-upload-label g-mt-30 text-center"><span class="glyphicon glyphicon-cloud-upload g-mr-3"></span> Upload Image</label>
    <%= f.file_field :main_image, class: "form-control image-upload", value: @countdown.main_image.url %>

    <div id="main-image-preview">
      <% if !@countdown.main_image.url %>
        <img class="imgFrame g-mt-20" src="/main_images/main_image1.jpg" alt="Selected Countdown Image" style="max-width: 150px; max-height: 150px;" >
      <% else %>
        <img class="imgFrame g-mt-20" src="<%=@countdown.main_image.thumb.url%>" alt="Selected Countdown Image" style="max-width: 150px; max-height: 150px;" >
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <p class="g-label">Countdown Image:</p>
    <p class="secondary-text g-ml-10">Choose one of our images or upload your own</p>
    <div>
      <div class="row background-image-scroll"> 
        <% 9.times do |n| %>
          <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
            <div class="text-center row">
              <img src="/background_images/background_image<%=n + 1%>.jpg" alt="Default Background Image" style="width: 120px; height: 120px;" class="g-mb-5 default-image imgFrame">
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="text-center">
      <label for="countdown_background_image" class="btn font-size-16 font-weight-600 g-mb-10 g-btn-secondary image-upload-label g-mt-30 text-center"><span class="glyphicon glyphicon-cloud-upload g-mr-3"></span> Upload Image</label>
  		<%= f.file_field :background_image, class: "form-control image-upload" %>

      <div id="background-image-preview">
        <% if !@countdown.background_image.url %>
          <img class="imgFrame g-mt-20" src="/background_images/background_image1.jpg" alt="Selected Background Image" style="max-width: 150px; max-height: 150px;">
        <% else %>
          <img class="imgFrame g-mt-20" src="<%=@countdown.background_image.url%>" alt="Selected Background Image" style="max-width: 150px; max-height: 150px;">
        <% end %>
      </div>
    </div>

      <%#= f.label :background_image, "Background Image:" %>
  		<%#= f.file_field :background_image, class: "form-control image-upload" %>
  </div>
           
  <div class="text-center g-mt-40">
    <button type="button" id="previewBtn" class= "btn g-btn-secondary font-size-16 g-mr-20 font-weight-600 g-mb-10">Preview</button>
            
    <button type="submit" id="nextBtn" class="next-prev-btn btn font-size-16 font-weight-400 g-mb-10 g-btn-primary">Submit</button>
  </div>
<% end %>

app/views/countdowns/index.html.erb
<h1>Countdown#index</h1>
<p>Find me in app/views/countdown/index.html.erb</p>

app/views/countdowns/new.html.erb
<%= render '/countdowns/preview.html.erb' %>
<% provide(:title, "New Countdown") %>

<%= form_for(@countdown, :html => { class: "g-primary-card countdown-form", id: "regForm" }) do |f| %>

  <h1>New Countdown</h1>

  <%= render 'shared/error_messages' %>

  <div class="tab">
    <div class="form-group">
      <%= f.label :name %>
  	  <%= f.text_field :name, class: "form-control", placeholder: "Enter countdown name" %>
  	</div>
  
    <div class="form-group">
  	  <%= f.label :date %>
      <%= f.date_field :date, class: "form-control" %>
    </div>
  </div>

  <div class="tab g-mb-40 text-center"> 
    <div class="form-group">
  	  <%= f.label :title_color, "Title Color:" %>
      <div>
  		  <%= f.text_field :title_color, value: "#ffffff", class: "form-control", style: "display: inline; width: 66%;" %>
      </div>
  	</div>
    
  
    <div class="form-group">
  		<%= f.label :labels_color, "Labels' Color:" %>
      <div>
        <%= f.text_field :labels_color, value: "#ffffff", class: "form-control", style: "display: inline; width: 66%;" %>
      </div>
    </div>

    <div class="form-group">
  	  <%= f.label :time_color, "Time Color:" %>
      <div>
  		  <%= f.text_field :time_color, value: "#cccccc", class: "form-control", style: "display: inline; width: 66%;" %>
      </div>
    </div>
  
    <div class="form-group">
  	  <%= f.label :clock_background_color, "Clock Background Color:" %>
      <div>
        <%= f.text_field :clock_background_color, value: "#333333", class: "form-control", style: "display: inline; width: 66%;" %>
      </div>
    </div>
  </div>

  <div class="tab">
    <div class="form-group">
      <%= f.hidden_field :local_main_image, class: "hidden", value: "/main_images/main_image1.jpg" %>
      <%= f.hidden_field :local_background_image, class: "hidden", value: "/background_images/background_image1.jpg" %>

      <span class="g-label g-mr-40">Countdown Thumbnail:</span>
      <label class="switch text-center">
        <input type="checkbox" id="main-image-switch" checked>
        <span class="slider round"></span>
      </label>
<div id="main-image-select">
      <p class="secondary-text g-ml-10">Choose one of our images or upload your own</p>
      <div>
      <div class="row main-image-scroll"> 
        <% 7.times do |n| %>
          <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
            <div class="text-center row">
              <img src="/main_images/main_image<%=n + 1%>.jpg" alt="Default Countdown Image" style="max-width: 120px; max-height: 120px;" class="g-mb-5 default-image imgFrame">
            </div>
          </div>
        <% end %>
      </div>
      </div>
      <div class="text-center">
        <label for="countdown_main_image" class="btn font-size-16 font-weight-600 g-mb-10 g-btn-secondary image-upload-label g-mt-30 text-center"><span class="glyphicon glyphicon-cloud-upload g-mr-3"></span> Upload Image</label>
  		  <%= f.file_field :main_image, class: "form-control image-upload" %>

        <div id="main-image-preview">
          <img class="imgFrame g-mt-20" src="/main_images/main_image1.jpg" alt="Selected Countdown Image" style="max-width: 150px; max-height: 150px;" >
        </div>
      </div>
    </div>
</div>

    <div class="form-group">
      <p class="g-label">Countdown Image:</p>
      <p class="secondary-text g-ml-10">Choose one of our images or upload your own</p>
      <div>
        <div class="row background-image-scroll"> 
          <% 9.times do |n| %>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
              <div class="text-center row">
                <img src="/background_images/background_image<%=n + 1%>.jpg" alt="Default Background Image" style="width: 120px; height: 120px;" class="g-mb-5 default-image imgFrame">
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <div class="text-center">
        <label for="countdown_background_image" class="btn font-size-16 font-weight-600 g-mb-10 g-btn-secondary image-upload-label g-mt-30 text-center"><span class="glyphicon glyphicon-cloud-upload g-mr-3"></span> Upload Image</label>
  		  <%= f.file_field :background_image, class: "form-control image-upload" %>

        <div id="background-image-preview">
          <img class="imgFrame g-mt-20" src="/background_images/background_image1.jpg" alt="Selected Background Image" style="max-width: 150px; max-height: 150px;" >
        </div>
      </div>

      <%#= f.label :background_image, "Background Image:" %>
  		<%#= f.file_field :background_image, class: "form-control image-upload" %>
  	</div>
  </div>
           
  <div class="text-center g-mt-40"> 
    <button type="button" id="prevBtn" class= "next-prev-btn btn font-size-16 g-mr-20 font-weight-400 g-mb-10"><span class="glyphicon glyphicon-chevron-left"></span> Previous</button> 
            
    <button type="button" id="nextBtn" class="next-prev-btn btn font-size-16 font-weight-400 g-mb-10 g-btn-primary">Next <span class="glyphicon glyphicon-chevron-right"></span></button><br>
    <button type="button" id="previewBtn" class= "g-btn-secondary btn btn-block font-size-16 g-mb-10">Preview</button> 

  </div>
 
  <!--<button type="button" id="previewBtn" class= "text-center g-btn-secondary btn btn-block font-size-16 g-mr-20 font-weight-400 g-mb-10">Preview</button>-->


  <!-- Circles which indicates the steps of the form: -->
  <div style="text-align:center;margin-top:40px; margin-right: 0; margin-left: 0;">
    <span class="step"></span>
    <span class="step"></span>
    <span class="step"></span>
  </div>
<% end %>

app/views/countdowns/next.js.erb
<% if !@valid %>
  $('#error_explanation').remove();
  $('#regForm').prepend("<%= escape_javascript render(:partial => '/shared/error_messages') %>");
<% end %>

app/views/countdowns/preview.html.erb
<img src=<%=@main_image%>>

app/views/countdowns/preview.js.erb
<% if @valid %>
  $("#preview-modal .modal-body").append("<%= escape_javascript render(:partial => '/countdowns/countdown', locals: { countdown: @countdown }) %>");
  $("#preview-modal").modal('show'); 
<% else %>
  $('#error_explanation').remove();
  var html = "<div id='error_explanation'><ul><li>" + data.error + "</li></ul></div>";
  $('#regForm h1').after(html);
<% end %>

app/views/countdowns/show.html.erb
<% content_for :head do %>
  <meta property="og:title" content="Mark The Date!" />
  <meta property="og:description" content="<%= @countdown.name %>" />
  <meta property="og:image" content="<%= @countdown.main_image.url %>" />
  <script type='text/javascript' src='//platform-api.sharethis.com/js/sharethis.js#property=5b121e81093c0e0011b0377d&product=inline-share-buttons' async='async'></script>
<% end %>
<span class="st_sharethis" st_url="http://sharethis.com" st_title="Sharing is great!" st_image="<%=@countdown.main_image.url%>"></span>
<div class="countdown" id="countdown-show" style='background: url(<%=@countdown.background_image.url%>'>
  <header class="masthead">
    <div class="intro-body">
      <div class="container">
        <div class="text-center">
          <% if @countdown.main_image.url %>
            <h3 class="brand-heading margin" style="color: <%=@countdown.title_color%>"><%=@countdown.name%></h3>
			      <img src="<%=@countdown.main_image.thumb.url%>"  class="img-responsive img-circle margin" alt="Me" style="display:inline" width="250" height="250">
            <div class="text-center">
              <div class="flip-counter clock flip-clock-wrapper" style=""></div>
            </div>
          <% else %>
            <h3 class="brand-heading g-mb-50" style="color: <%=@countdown.title_color%>"><%=@countdown.name%></h3>
            <div class="text-center g-mt-100">
              <div class="flip-counter clock flip-clock-wrapper" style=""></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </header>
</div>


<section class="cta" id="cta">
  <div class="cta-content">
    <div class="container">
      <h2 class="white">Use it on your website</h2>
      <p class="white">Get the source code and use the countdown on your personal website!</p>
      <%= link_to countdown_path(@countdown.id, format: :zip) do %>
		  <button type="button" id="cta-btn" class= "btn btn-lg g-btn-primary font-size-16 g-mr-20 font-weight-600"><span class="glyphicon glyphicon-download"></span> Download</button>
      <% end %>
    </div>
  </div>
  <div class="overlay"></div>
  <div class="sm-wrapper text-center">
    <h4 class="white g-mb-25 font-weight-600 g-mt-40"> Share the countdown on social media </h4>
	  <ul>
      <li class="facebook"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></li>
      <li class="twitter"><i class="fa fa-twitter fa-2x" aria-hidden="true"></i></li>
      <li class="instagram"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></li>
      <li class="google"><i class="fa fa-google fa-2x" aria-hidden="true"></i></li>
      <li class="whatsapp"><i class="fa fa-whatsapp fa-2x" aria-hidden="true"></i></li>
    </ul>
	</div>
</section>

<% if current_user == @countdown.user %>
  <div class="text-center container g-primary-card g-mt-40 g-mb-40 g-pa-20">
    <h2 class="text-center g-mb-20">Customize Countdown</h2>
    <%= link_to edit_countdown_path(@countdown.id), style: "color: #fff;" do %>

      <button type="button" class= "btn g-pa-8 g-btn-primary font-size-16 g-mr-20 font-weight-600 g-mb-10 g-w-33"><span class="glyphicon glyphicon-edit"></span> Edit</button> 
    <% end %>
    <%= link_to @countdown, method: :delete,
                            style: "color: #394251;",
																				data: { confirm: "You sure?" } do %>
      <button type="button" class="btn g-pa-8 font-size-16 font-weight-600 g-mb-10 g-w-33"><span class="glyphicon glyphicon-remove"></span> Delete</button><br>
    <% end %>
  </div>
<% end %>

<div class="sharethis-inline-share-buttons"></div>


<%#= render 'countdown_actions_modal' %>


<input id="countdown-date" type="hidden" value="<%= @countdown.date %>">

<style>
  .navbar {
    margin-bottom: 0 !important;
  }

  .flip-clock-label { 
    color: <%= @countdown.labels_color %> !important;
  }

  .flip-clock-wrapper ul li a div div.inn {
    color: <%= @countdown.time_color %> !important;
    background-color: <%= @countdown.clock_background_color %> !important;
  }
</style>