config/routes.rb
Rails.application.routes.draw do

  resources :countdowns, only: [:show, :index, :edit, :create, :destroy, :new, :update]
  get '/countdowns/new/next', to: 'countdowns#next', as: :next
  get '/countdowns/new/preview', to: 'countdowns#preview', as: :preview

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  devise_scope :user do
    authenticated :user do
      root 'countdowns#index'
    end
		
    unauthenticated do
      root 'devise/sessions#new'
    end
  end

  resources :users, only: [:edit, :show, :update]

  # Begin StaticPages Controller
  get '/landing', to: 'static_pages#landing', as: :landing
	get '/about', to: 'static_pages#about', as: :about
	get '/attributions', to: 'static_pages#attributions', as: :attributions
  get '/random', to: 'static_pages#random', as: :random
  # End StaticPages Controller


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :countdowns, dependent: :destroy
  before_save { self.email = email.downcase }
  #validates :username, presence: true, length: { minimum: 5, maximum: 18 },
	#										uniqueness: true
  validates :email, presence: true, length: { maximum: 255 },
										uniqueness: { case_sensitive: false }
  #validates :bio, length: { maximum: 500 }
  validates :name, length: { maximum: 70 }

  #validate :profile_image_size

  private

    # Validates the size of an uploaded image
=begin
		def profile_image_size
			if self.profile_image.size > 5.megabytes
				errors.add(:profile_image, "should be less than 5MB")
			end
		end
=end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,	 only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      # Handle a successful update
      flash[:success] = "Your profile has been updated successfully."
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :name)
    end
end

app/views/users/edit.html.erb
<% provide(:title, "Edit Profile") %>

<div class="custom-form">
  <div class="limiter">
  	<div class="container-login100">
  		<div class="wrap-login100 primary-bs">
  			
				<%= render 'shared/edit_account_header' %>	

  			<%= form_for(@user, :html => { :method => :patch, :class => 'login100-form validate-form', novalidate: :true }, url: user_path(current_user.id)) do |f| %>

    			<%= render 'shared/error_messages' %>
  
  				<div class="field wrap-input100 validate-input m-b-18">
						<span class="label-input100" style="font-size: 12px; width:90px;">Username</span>
    				<%= f.text_field :username, autocomplete: "off", class: "input100", placeholder: "Enter new username" %>
						<span class="focus-input100"></span>
  				</div>

  				<div class="field wrap-input100 validate-input m-b-18">
						<span class="label-input100" style="font-size: 12px; width:90px;">Name</span>
    				<%= f.text_field :name, autocomplete: "off", class: "input100", placeholder: "Enter your name" %>
						<span class="focus-input100"></span>
  				</div> 
  				
					<div class="actions container-login100-form-btn">
  					<%= f.submit "Save Changes", class: "btn g-mb-10 g-mt-20 font-size-16 font-weight-400 g-btn-primary" %>
  				</div>

				<% end %>	
  		</div>
  	</div>
  </div>	
</div>

app/views/users/show.html.erb
<% provide(:title, "Progress") %>
<!--
  <h1 class="text-center font-weight-600">Countdowns</h1>
-->
<div class="countdown-flickity" id="carousel">
  <% @user.countdowns.each do |countdown| %>
    <%#= link_to countdown_path(countdown.id) do %>
    <div class="countdown" style='background: url(<%=countdown.background_image.url%>'>
      <%= link_to countdown_path(countdown.id) do %>
      <header class="masthead">
        <div class="intro-body">
          <div class="container">
            <div class="text-center">
              <% if countdown.main_image.url %>
                <h3 class="brand-heading margin" style="color: <%=countdown.title_color%>"><%=countdown.name%></h3>
			          <img src="<%=countdown.main_image.thumb.url%>"  class="img-responsive img-circle margin" alt="Me" style="display:inline" width="250" height="250">
                <div class="text-center">
                  <div class="flip-counter clock flip-clock-wrapper" id="clock-<%=countdown.id%>"></div>
                </div>
              <% else %>
                <h3 class="brand-heading g-mb-50" style="color: <%=countdown.title_color%>"><%=countdown.name%></h3>
                <div class="text-center g-mt-100">
                  <div class="flip-counter clock flip-clock-wrapper" id="clock-<%=countdown.id%>"></div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </header>
      <% end %>
    </div>
    
  <% end %>
  <% @user.countdowns.each do |countdown| %>
    <input class="countdown-date-element" id="date-<%=countdown.id%>" type="hidden" value="<%= countdown.date %>">


    <style>
      #clock-<%=countdown.id%> .flip-clock-label { 
        color: <%= countdown.labels_color %> !important;
      }

      #clock-<%=countdown.id%> ul li a div div.inn {
        color: <%= countdown.time_color %> !important;
        background-color: <%= countdown.clock_background_color %> !important;
      }
    </style>
  <% end %>
</div>

<style>
  .navbar {
    margin-bottom: 0 !important;
  }
</style>