config/routes.rb
Rails.application.routes.draw do

  resources :countdowns, only: [:show, :index, :edit, :create, :destroy, :new, :update]
  get '/countdowns/new/next', to: 'countdowns#next', as: :next
  get '/countdowns/new/preview', to: 'countdowns#preview', as: :preview

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  devise_scope :user do
    authenticated :user do
      root 'countdowns#index'
    end
		
    unauthenticated do
      root 'devise/sessions#new'
    end
  end

  resources :users, only: [:edit, :show, :update]

  # Begin StaticPages Controller
  get '/landing', to: 'static_pages#landing', as: :landing
	get '/about', to: 'static_pages#about', as: :about
	get '/attributions', to: 'static_pages#attributions', as: :attributions
  get '/random', to: 'static_pages#random', as: :random
  # End StaticPages Controller


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<% if !landing_page? && !about_page? %>
	<hr class="default-border">
<% end %>
<footer class="footer-container" role="contentinfo">
	<div class="f-1-ch-1 f-1-ch-2 text-center" style="max-width: 935px;">
		<nav role="navigation col-md-">
			<ul>
				<li class="footer-item">
					<%= link_to "About", about_path %>
				</li>
				<li class="footer-item">
					<%= link_to "Attributions", attributions_path %>
				</li>
				<li class="footer-item">
					<%= link_to "Github", "https://github.com/raguila8/countdown_app" %>
				</li>
			</ul>
		</nav>
		<span class="copyright text-center">© 2018 Rodrigo Aguilar</span>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
  	<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
  		<%= link_to "COUNTDOWN", root_path, class: "navbar-brand" %>
   	</div>
		<div class="collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav navbar-right">
    		<li>
					<%= link_to "Browse", countdowns_path %>
				</li>
      
			<% if signed_in? %>

        <li>
          <%= link_to new_countdown_path do %>
            <span class="glyphicon glyphicon-plus-sign g-mr-5"></span>
            <span>New Countdown</span>
          <% end %>
        </li>

				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<span class="glyphicon glyphicon-user g-mr-5"></span>
						<span><%=current_user.username%></span>
						<span class="caret"></span>
					</a>
        	<ul class="dropdown-menu">
          	<li class="g-mh-20">
							<%= link_to current_user do %>
                <span class="glyphicon glyphicon-hourglass g-mr-5"></span>
                <span>My Countdowns</span>
              <% end %>
						</li>	

          	<li class="g-mh-20">
							<%= link_to edit_user_registration_path do %>
                <span class="glyphicon glyphicon-cog g-mr-5"></span>
                <span>Account</span>
              <% end %>
						</li>

          	<li class="g-mh-20">
							<%= link_to destroy_user_session_path, method: :delete do %>
                <span class="c-danger glyphicon glyphicon-log-out g-mr-5"></span>
                <span class="c-danger">Log Out</span>
              <% end %>
						</li>
       		</ul>
				</li>
			<% else %>
        <li>
					<%= link_to "Log In", new_user_session_path, id: 'secondary-btn', class: "g-btn-small g-ml-16 font-weight-600" %>
				</li>

				<li>
					<%= link_to "Sign up", new_user_registration_path, id: 'signup-btn', class: "g-btn-small g-ml-16 font-weight-600" %>
				</li>
			<% end %>
      <!--
			<div class="min-w-250 max-w-300 col-sm-3 col-md-3 pull-left navbar-form-container">
      	<form class="navbar-form" role="search">
        	<div class="input-group">
          	<input type="text" class="form-control" placeholder="Search" name="q" id="main-search">
            <div class="input-group-btn">
            	<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
          </div>
        </form>
      </div>
      -->

    </ul>
		</div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= content_for?(:head) ? yield(:head) : '' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= flash_messages %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>